### PR TITLE
Ollama Support: system prompt + testing

### PR DESCRIPTION
**Pull request by antoninoLorenzo**
I implemented the system prompt for `ollama/phi3` model and added a test to ensure correct formatting (passed); next I will implement user prompt for phi3.

### CODE REVIEW

**Comment by killind-dev** [comment]
Hey @antoninoLorenzo looks good to me! At some point we need to implement agent regression tests (not sure how), but for now could you just try with anthropic and openai to be sure?

**Comment by killind-dev** [comment]
Otherwise looking solid

**Comment by antoninoLorenzo** [comment]
@killind-dev I can't test anthropic and openai models given that I do not have a subscription; about regression test what approach are you thinking about?

**Comment by killind-dev** [comment]
Sounds good, I'll test it and merge if we are all good. Regarding regression tests I'll open another issue and comment it here

**Comment by killind-dev** [comment]
#40 @antoninoLorenzo heres the issue for regression testing

**Comment by antoninoLorenzo** [comment]
> #40 @antoninoLorenzo heres the issue for regression testing

Got it, once the Ollama support is completed (at least bare minimum) I can work on the regression tests for it; I can structure it in a way that Is easy to replicate with other models.

However other then that if there aren't any issues with the pull request I will wait the merge so I can update my fork.

**Comment by Mihir1003** [comment]
I can test the pr for you. If everything is fine I'll merge.

**Comment by antoninoLorenzo** [comment]
> I can test the pr for you. If everything is fine I'll merge.

Great, however i didn't really touched openai and anthropic stuff.

**Comment by Mihir1003** [comment]
ok then ill merge it!

**Comment by akiradev0x** [comment]
@antoninoLorenzo yo whats your twitter? would love to should you out when we release this pr

**Comment by antoninoLorenzo** [comment]
> @antoninoLorenzo yo whats your twitter? would love to should you out when we release this pr

Honestly I never made and account 😅 that's not used much Italy

**Comment by akiradev0x** [comment]
Ok sounds good

**Comment by antoninoLorenzo** [comment]
@akiradev0x however yesterday I started integrating Ollama with the `PlanningAgent` class.
I took as reference the version in `agent.py` however the prompts used were different; what Is exactly the difference between Planning and Task agent?

**Pull request merged**
